# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8yvpMsYcPRBaNdBb9blJrdgsvV3b36E
"""

import os
import matplotlib.pyplot as plt
import numpy as np

# Configurar ruta a la carpeta 'figures'
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
FIGURES_DIR = os.path.join(BASE_DIR, "..", "figures")
os.makedirs(FIGURES_DIR, exist_ok=True)

def train_lms(X, d, initial_weights, mu, alpha=0.0, use_momentum=False, target_xi=0.1, max_epochs=300):
    """
    Entrena un modelo Adaline usando LMS.
    Permite alternar entre descenso de gradiente estándar y el método de momento.
    """
    w = initial_weights.copy()
    delta_w = np.zeros_like(w)  # Almacena el gradiente anterior para el momento
    xi_history = []
    epoch = 0

    # Error promedio inicial
    y_init = np.dot(X, w)
    e_init = d - y_init
    xi_p = np.mean(e_init**2)
    xi_history.append(xi_p)

    while xi_p > target_xi and epoch < max_epochs:
        for k in range(len(X)):
            x_k = X[k]
            d_k = d[k]
            y_k = np.dot(w, x_k)
            e_k = d_k - y_k

            # Componente del gradiente instantáneo
            gradient = 2 * mu * e_k * x_k

            if use_momentum:
                # Regla con factor de momento
                delta_w = gradient + (alpha * delta_w)
                w = w + delta_w
            else:
                # Regla estándar (Paso más descendente)
                w = w + gradient

        # Error cuadrático medio de la época
        y_epoch = np.dot(X, w)
        e_epoch = d - y_epoch
        xi_p = np.mean(e_epoch**2)

        # Evitar desbordamiento numérico por la divergencia de mu=0.5
        if np.isnan(xi_p) or np.isinf(xi_p):
            break

        xi_history.append(xi_p)
        epoch += 1

    return w, xi_history, epoch

def plot_comparison(gate_name, d, X, mu, alpha, initial_weights, target_xi=0.1, max_epochs=300):
    """Genera una única gráfica comparando LMS estándar vs Momento para una compuerta."""
    fig, ax = plt.subplots(figsize=(10, 6))
    fig.suptitle(f"Compuerta {gate_name} - Comparación de Aprendizaje ($\\mu = {mu}$)", fontsize=14, fontweight="bold")

    # 1. Entrenamiento Estándar (Sin momento)
    _, xi_hist_std, ep_std = train_lms(X, d, initial_weights, mu, use_momentum=False, target_xi=target_xi, max_epochs=max_epochs)

    # 2. Entrenamiento con Momento
    _, xi_hist_mom, ep_mom = train_lms(X, d, initial_weights, mu, alpha=alpha, use_momentum=True, target_xi=target_xi, max_epochs=max_epochs)

    # Trazado de líneas en la misma gráfica
    ax.plot(
        range(len(xi_hist_std)), xi_hist_std,
        color="#1f77b4", linewidth=2,
        label=f"LMS Estándar (Épocas: {ep_std})"
    )

    ax.plot(
        range(len(xi_hist_mom)), xi_hist_mom,
        color="#ff7f0e", linewidth=2, linestyle="--",
        label=f"LMS con Momento $\\alpha={alpha}$ (Épocas: {ep_mom})"
    )

    ax.axhline(y=target_xi, color="r", linestyle=":", alpha=0.8, label=f"Meta $\\xi_p \le {target_xi}$")

    ax.set_title(f"Dinámica de Error Cuadrático Medio ($\\xi_p$)", fontsize=11)
    ax.set_xlabel("Épocas (epoch)")
    ax.set_ylabel("$\\xi_p$ (Escala Logarítmica)")
    ax.grid(True, linestyle=":", alpha=0.6)
    ax.legend(loc="upper right")

    # IMPORTANTE: Usamos escala logarítmica porque en tu artículo documentaste que
    # mu=0.5 provoca divergencias explosivas (valores de hasta 1e180).
    # La escala lineal ocultaría la meta de 0.1.
    ax.set_yscale('log')

    plt.tight_layout()
    filepath = os.path.join(FIGURES_DIR, f"comparativa_momento_{gate_name.lower()}.png")
    plt.savefig(filepath, dpi=300, bbox_inches="tight")
    plt.show()

def main():
    X = np.array([[1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]])

    # Reducido únicamente a las 3 compuertas solicitadas
    gates = {
        "AND": np.array([0, 0, 0, 1]),
        "OR": np.array([0, 1, 1, 1]),
        "XOR": np.array([0, 1, 1, 0]),
    }

    # Parámetros del experimento
    mu_fijo = 0.5
    alpha_momento = 0.8  # Puedes ajustar este hiperparámetro (usualmente entre 0.5 y 0.9)
    target_xi = 0.1
    max_epochs = 300

    np.random.seed(42)
    initial_weights = np.random.rand(3) * 0.001

    for gate_name, d in gates.items():
        plot_comparison(
            gate_name, d, X, mu_fijo, alpha_momento, initial_weights, target_xi, max_epochs
        )

if __name__ == "__main__":
    main()